apiVersion: v1
kind: Secret
metadata:
  name: metrum-ai-router-secrets
  labels:
    app.kubernetes.io/name: metrum-ai-router
type: Opaque
stringData:
  env.json: |
    {
      "OPENAI_API_KEY": "",
      "OPENROUTER_API_KEY": ""
    }
