// Copyright 2026 Metrum AI
// SPDX-License-Identifier: Apache-2.0

package smartrouterctl

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeHelmChart emits a Level-1 Helm chart scaffold under outDir/charts/smart-llmrouter.
// The chart packages the existing router image contract; it does not change router core.
func writeHelmChart(outDir string, intent *StackIntent) ([]string, error) {
	chartDir := filepath.Join(outDir, "charts", "smart-llmrouter")
	templates := filepath.Join(chartDir, "templates")
	if err := os.MkdirAll(templates, 0o755); err != nil {
		return nil, err
	}

	caddyEnabled := intent.Edge == "caddy"
	ingressEnabled := intent.Edge == "ingress"
	gpuProfile := "none"
	if intent.GPUOperator.Enabled || intent.Profile == "nvidia-local-serving" {
		gpuProfile = "nvidia-compatible"
	}
	imageRepo, imageTag := splitImage(intent.RouterImage)

	files := map[string]string{
		"Chart.yaml": fmt.Sprintf(`apiVersion: v2
name: smart-llmrouter
description: Metrum AI Router Level-1 Helm chart (generated by metrum-ai-routerctl blueprint render)
type: application
version: 0.1.0
appVersion: "generated"
`),
		"values.yaml": fmt.Sprintf(`# Generated values for profile %s. Production must pin image.digest.
image:
  repository: %s
  tag: %s
  digest: ""
  pullPolicy: IfNotPresent

replicaCount: 1

runtimeSecret:
  name: smart-llmrouter-secrets

config:
  # Use existingSecretKey=config.yaml when the runtime Secret owns all runtime files.
  existingConfigMap: smart-llmrouter-config
  existingSecretKey: ""

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

usageDatabase:
  mode: %s
  existingSecret: ""

service:
  enabled: true
  type: ClusterIP
  port: 80

caddy:
  enabled: %v
  image:
    repository: caddy
    tag: "2.9.1"
    digest: ""
  existingConfigMap: ""
  tls:
    mode: acme
    existingSecret: ""

ingress:
  enabled: %v
  className: ""
  hosts:
    - host: router.example.com
      paths:
        - path: /
          pathType: Prefix

gateway:
  httpRoute:
    enabled: false

probes:
  enabled: true

pdb:
  minAvailable: 1

hpa:
  enabled: false

networkPolicy:
  enabled: true

gpuProfile: %s
serving:
  assumeNvidiaAvailable: true

# Router Pod MUST NOT request nvidia.com/gpu / amd.com/gpu.
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi
`, intent.Profile, yamlScalar(imageRepo), yamlScalar(imageTag), intent.UsageDriver, caddyEnabled, ingressEnabled, gpuProfile),
		"templates/_helpers.tpl": `{{- define "smart-llmrouter.name" -}}
smart-llmrouter
{{- end -}}
{{- define "smart-llmrouter.labels" -}}
app.kubernetes.io/name: {{ include "smart-llmrouter.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
`,
		"templates/serviceaccount.yaml": `apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smart-llmrouter.name" . }}
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
automountServiceAccountToken: false
`,
		"templates/deployment.yaml": `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-llmrouter.name" . }}
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smart-llmrouter.name" . }}
  template:
    metadata:
      labels:
        {{- include "smart-llmrouter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "smart-llmrouter.name" . }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: router
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.image.digest }}
          # Prefer digest pins in production overlays.
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config", "/app/config/config.yaml"]
          ports:
            - name: http
              containerPort: 8080
          {{- if .Values.probes.enabled }}
          readinessProbe:
            httpGet: { path: /readyz, port: http }
          livenessProbe:
            httpGet: { path: /healthz, port: http }
          startupProbe:
            httpGet: { path: /readyz, port: http }
            failureThreshold: 24
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: secrets
              mountPath: /app/config/env.json
              subPath: env.json
              readOnly: true
            - name: state
              mountPath: /app/state
            - name: logs
              mountPath: /app/logs
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          {{- if .Values.config.existingSecretKey }}
          secret:
            secretName: {{ .Values.runtimeSecret.name }}
            items:
              - key: {{ .Values.config.existingSecretKey }}
                path: config.yaml
          {{- else }}
          configMap:
            name: {{ .Values.config.existingConfigMap }}
          {{- end }}
        - name: secrets
          secret:
            secretName: {{ .Values.runtimeSecret.name }}
            defaultMode: 0400
        - name: state
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "smart-llmrouter.name" . }}-state
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
`,
		"templates/service.yaml": `{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-llmrouter.name" . }}
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "smart-llmrouter.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
`,
		"templates/pdb.yaml": `apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "smart-llmrouter.name" . }}
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smart-llmrouter.name" . }}
`,
		"templates/pvc.yaml": `{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "smart-llmrouter.name" . }}-state
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
`,
		"templates/NOTES.txt": `Metrum AI Router chart generated by metrum-ai-routerctl.

1. Create Secret {{ .Values.runtimeSecret.name }} with keys config.yaml (when using secret key) and env.json.
2. Ensure usageDatabase.mode matches server.usage_db.driver in the mounted config.
3. SQLite requires replicaCount=1 and Recreate (chart default).
4. Router Pod does not request GPUs; gpuProfile={{ .Values.gpuProfile }} is documentation/serving guidance only.
5. Enable at most one of caddy.enabled, ingress.enabled, gateway.httpRoute.enabled.
`,
	}

	if caddyEnabled {
		files["templates/caddy-deployment.yaml"] = `{{- if .Values.caddy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-llmrouter.name" . }}-caddy
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "smart-llmrouter.name" . }}-caddy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "smart-llmrouter.name" . }}-caddy
        app.kubernetes.io/component: caddy
    spec:
      containers:
        - name: caddy
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag }}"
          ports:
            - name: https
              containerPort: 443
            - name: http
              containerPort: 80
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
              readOnly: true
      volumes:
        - name: caddyfile
          configMap:
            name: {{ default (printf "%s-caddy" (include "smart-llmrouter.name" .)) .Values.caddy.existingConfigMap }}
{{- end }}
`
		files["templates/caddy-service.yaml"] = `{{- if .Values.caddy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-llmrouter.name" . }}-caddy
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
    app.kubernetes.io/component: caddy
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ include "smart-llmrouter.name" . }}-caddy
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: http
      port: 80
      targetPort: http
{{- end }}
`
		files["templates/caddyfile-configmap.yaml"] = `{{- if and .Values.caddy.enabled (not .Values.caddy.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smart-llmrouter.name" . }}-caddy
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
data:
  Caddyfile: |
    :80 {
      reverse_proxy {{ include "smart-llmrouter.name" . }}:80 {
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}
        header_up X-Request-Id {http.request.header.X-Request-Id}
      }
    }
{{- end }}
`
	}

	if ingressEnabled {
		files["templates/ingress.yaml"] = `{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "smart-llmrouter.name" . }}
  labels:
    {{- include "smart-llmrouter.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "smart-llmrouter.name" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
`
	}

	written := make([]string, 0, len(files))
	for rel, body := range files {
		path := filepath.Join(chartDir, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return nil, err
		}
		written = append(written, filepath.ToSlash(filepath.Join("charts", "smart-llmrouter", rel)))
	}
	return written, nil
}

func splitImage(image string) (repo, tag string) {
	image = strings.TrimSpace(image)
	if image == "" {
		return "registry.example.com/smart-llmrouter", "latest"
	}
	// Keep digest out of tag; chart values.digest is separate.
	if i := strings.Index(image, "@"); i >= 0 {
		image = image[:i]
	}
	if i := strings.LastIndex(image, ":"); i > 0 && !strings.Contains(image[i:], "/") {
		return image[:i], image[i+1:]
	}
	return image, "latest"
}

func yamlScalar(v string) string {
	if v == "" || strings.ContainsAny(v, ":\n#\"'{}\t ") || strings.Contains(v, "<") {
		return fmt.Sprintf("%q", v)
	}
	return v
}
