// Copyright 2026 Metrum AI
// SPDX-License-Identifier: Apache-2.0

package smartrouterctl

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeOperatorScaffold emits Level-2 CRD definitions and example CRs that map
// only to existing router config fields. It does not ship a controller binary or
// add a router Kubernetes dependency.
func writeOperatorScaffold(outDir string, intent *StackIntent) ([]string, error) {
	opDir := filepath.Join(outDir, "operator")
	crds := filepath.Join(opDir, "crds")
	samples := filepath.Join(opDir, "samples")
	for _, dir := range []string{opDir, crds, samples} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, err
		}
	}

	readme := `# Optional Metrum AI Router operator scaffold

Generated by ` + "`metrum-ai-routerctl blueprint render`" + `.

## Authority

- API group: ` + "`router.metrum.ai/v1alpha1`" + `
- CRDs serialize only to existing router YAML fields.
- The operator's required output is a valid ` + "`config.yaml`" + ` ConfigMap/Secret key.
- Topology (Deployment, Service, Caddy/Ingress, PVC, HPA) remains chart-owned.
- This scaffold does **not** install a controller-runtime binary into the router
  image and does **not** give the serving router a Kubernetes client.

## When required

Enable ` + "`packaging.operator.enabled`" + ` when in-cluster upstream discovery must keep
provider URLs current. Until a portable discovery field exists in router config,
keep Level-1 Helm/Kustomize as the primary packaging path.

## Install CRDs only (no controller)

` + "```bash" + `
kubectl apply -f operator/crds/
kubectl apply -f operator/samples/
` + "```" + `

Deleting the operator must leave the running router serving from its mounted config.
`

	crdSmartRouter := `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: smartrouters.router.metrum.ai
spec:
  group: router.metrum.ai
  names:
    kind: SmartRouter
    listKind: SmartRouterList
    plural: smartrouters
    singular: smartrouter
    shortNames: ["sr"]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: SmartRouter maps to router server, providers, state_path, and account directory fields only.
          properties:
            apiVersion: { type: string }
            kind: { type: string }
            metadata: { type: object }
            spec:
              type: object
              properties:
                server: { type: object, x-kubernetes-preserve-unknown-fields: true }
                state_path: { type: string }
                providers: { type: object, x-kubernetes-preserve-unknown-fields: true }
                users: { type: array, items: { type: object, x-kubernetes-preserve-unknown-fields: true } }
                projects: { type: array, items: { type: object, x-kubernetes-preserve-unknown-fields: true } }
                project_memberships: { type: array, items: { type: object, x-kubernetes-preserve-unknown-fields: true } }
              # Prohibited Kubernetes-only fields (replicas, ingress, licenseSecretRef,
              # telemetry_sinks, usageStore) MUST NOT be added until router schema owns them.
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type: { type: string }
                      status: { type: string }
                      reason: { type: string }
                      message: { type: string }
      subresources:
        status: {}
`

	crdModelGroup := `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modelgroups.router.metrum.ai
spec:
  group: router.metrum.ai
  names:
    kind: ModelGroup
    listKind: ModelGroupList
    plural: modelgroups
    singular: modelgroup
    shortNames: ["mg"]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: ModelGroup.metadata.name becomes models.<name> in config.yaml.
          properties:
            apiVersion: { type: string }
            kind: { type: string }
            metadata: { type: object }
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                strategy: { type: string }
                attempt_timeout_ms: { type: integer }
                targets:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
`

	crdCallerToken := `apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: callertokens.router.metrum.ai
spec:
  group: router.metrum.ai
  names:
    kind: CallerToken
    listKind: CallerTokenList
    plural: callertokens
    singular: callertoken
    shortNames: ["ct"]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: CallerToken.spec serializes to one callers[] item. metadata.name MUST equal spec.id.
          properties:
            apiVersion: { type: string }
            kind: { type: string }
            metadata: { type: object }
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              required: [id, owner_user, project, token_sha256, allow]
              properties:
                id: { type: string }
                owner_user: { type: string }
                project: { type: string }
                environment: { type: string }
                status: { type: string }
                token_sha256: { type: string }
                token_id: { type: string }
                allow:
                  type: array
                  items: { type: string }
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
`

	sampleSR := fmt.Sprintf(`apiVersion: router.metrum.ai/v1alpha1
kind: SmartRouter
metadata:
  name: %s
  namespace: %s
spec:
  server:
    listen: ":8080"
    default_model_group: %q
    logging:
      path: /app/logs/requests.jsonl
    usage_db:
      enabled: true
      driver: %q
      path: /app/state/usage.sqlite
      migration_policy: deployment-job
    decision_telemetry:
      enabled: false
  state_path: /app/state/router-state.json
  providers: {}
  users:
    - id: local-operator
      name: Local Operator
      type: service_account
      status: active
  projects:
    - id: local
      name: Local
      status: active
  project_memberships:
    - user_id: local-operator
      project: local
      role: member
      status: active
`, intent.Namespace, intent.Namespace, intent.DefaultModelGroup, intent.UsageDriver)

	var sampleProviders strings.Builder
	var sampleGroups strings.Builder
	for _, model := range intent.ServingModels {
		providerName := "local-" + model.Name
		fmt.Fprintf(&sampleProviders, `  %s:
    base_url: %q
    dialect: openai-chat
    api_key: "${%s}"
    api_key_env: %s
    models:
      %s:
        model: %q
`, providerName, model.ServiceDNS, model.APIKeyEnv, model.APIKeyEnv, model.Name, model.ServedModelID)

		sampleGroups.WriteString(fmt.Sprintf(`---
apiVersion: router.metrum.ai/v1alpha1
kind: ModelGroup
metadata:
  name: %s
  namespace: %s
spec:
  strategy: static
  targets:
    - provider: %s
      model_ref: %s
      weight: 100
`, model.ModelGroup, intent.Namespace, providerName, model.Name))
	}
	sampleSR = strings.Replace(sampleSR, "  providers: {}\n", "  providers:\n"+sampleProviders.String(), 1)

	sampleCaller := fmt.Sprintf(`apiVersion: router.metrum.ai/v1alpha1
kind: CallerToken
metadata:
  name: local-operator-local-dev
  namespace: %s
spec:
  id: local-operator-local-dev
  owner_user: local-operator
  project: local
  environment: dev
  status: active
  token_sha256: "%s"
  token_id: rtr_metrum_local-operator_local_dev_k1
  allow:
%s`, intent.Namespace, strings.Repeat("0", 64), yamlStringList(intent.CallerAllow))

	files := map[string]string{
		"README.md":                readme,
		"crds/smartrouter.yaml":    crdSmartRouter,
		"crds/modelgroup.yaml":     crdModelGroup,
		"crds/callertoken.yaml":    crdCallerToken,
		"samples/smartrouter.yaml": sampleSR,
		"samples/modelgroups.yaml": sampleGroups.String(),
		"samples/callertoken.yaml": sampleCaller,
		"kustomization.yaml": `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/smartrouter.yaml
  - crds/modelgroup.yaml
  - crds/callertoken.yaml
`,
	}

	written := make([]string, 0, len(files))
	for rel, body := range files {
		path := filepath.Join(opDir, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return nil, err
		}
		written = append(written, filepath.ToSlash(filepath.Join("operator", rel)))
	}
	return written, nil
}

func yamlStringList(values []string) string {
	var b strings.Builder
	for _, v := range values {
		fmt.Fprintf(&b, "    - %s\n", v)
	}
	return b.String()
}
